import { describe, expect, it } from 'bun:test';
import { formatDocxMetadata } from './docx-metadata-to-markdown.ts';
import type { DocxMetadata } from './docx-metadata.ts';
import { formatPptxMetadata } from './pptx-metadata-to-markdown.ts';
import type { PptxMetadata } from './pptx-metadata.ts';
import { formatXlsxMetadata } from './xlsx-metadata-to-markdown.ts';
import type { XlsxMetadata } from './xlsx-metadata.ts';

const MACRO_LINE = '- `word/vbaProject.bin` — embedded VBA macro project; this file can execute code when opened, treat as untrusted';

// Exact-output tests against synthetic, fully-populated records. One assertion
// pins the whole rendered contract — section order, titles, the `### `/`\n\n`
// structure, the `---` prefix, every per-format table's columns + rows, and
// the trailing newline — killing the array/string/join/ternary mutants that
// loose `.toContain` assertions leave alive.

describe('formatDocxMetadata — exact output', () => {
  it('renders every section in order with exact tables, comment line, and macro warning', () => {
    const meta: DocxMetadata = {
      core: { creator: 'V' },
      app: { Application: 'Word' },
      custom: [{ name: 'C', value: 'cv' }],
      people: [{ author: 'A', providerId: 'P', userId: 'U' }],
      externalRels: [{ source: 's', type: 't', target: 'tg' }],
      comments: [{ id: '1', author: 'Au', initials: 'In', date: 'D', text: 'Tx' }],
      insertions: [{ id: '2', author: 'Ai', date: 'Di', text: 'Ti' }],
      deletions: [{ id: '3', author: 'Ad', date: 'Dd', text: 'Td' }],
      hiddenText: ['H'],
      textBoxes: ['TB'],
      headersFooters: [{ part: 'word/header1.xml', text: 'HF' }],
      fields: [{ source: 'fs', instruction: 'fi' }],
      bookmarks: [{ id: 'b', name: 'bn' }],
      macros: ['word/vbaProject.bin'],
    };
    expect(formatDocxMetadata(meta)).toBe(
      [
        '---',
        '',
        '## DOCX metadata',
        '',
        '### Core properties',
        '',
        '- **creator**: V',
        '',
        '### Application properties',
        '',
        '- **Application**: Word',
        '',
        '### Custom properties',
        '',
        '| name | value |',
        '| --- | --- |',
        '| C | cv |',
        '',
        '### People registry',
        '',
        '| author | providerId | userId |',
        '| --- | --- | --- |',
        '| A | P | U |',
        '',
        '### External relationships',
        '',
        '| source | type | target |',
        '| --- | --- | --- |',
        '| s | t | tg |',
        '',
        '### Comments',
        '',
        '- **id 1** — Au (In) @ D',
        '  > Tx',
        '',
        '### Tracked changes — insertions',
        '',
        '| id | author | date | text |',
        '| --- | --- | --- | --- |',
        '| 2 | Ai | Di | Ti |',
        '',
        '### Tracked changes — deletions',
        '',
        '| id | author | date | text |',
        '| --- | --- | --- | --- |',
        '| 3 | Ad | Dd | Td |',
        '',
        '### Hidden-formatted text (w:vanish)',
        '',
        '- H',
        '',
        '### Text boxes / shapes',
        '',
        '- TB',
        '',
        '### Headers & footers',
        '',
        '| part | text |',
        '| --- | --- |',
        '| word/header1.xml | HF |',
        '',
        '### Fields (MERGEFIELD / HYPERLINK / DOCVARIABLE)',
        '',
        '| source | instruction |',
        '| --- | --- |',
        '| fs | fi |',
        '',
        '### Bookmarks',
        '',
        '| id | name |',
        '| --- | --- |',
        '| b | bn |',
        '',
        '### Macros (VBA)',
        '',
        MACRO_LINE,
        '',
      ].join('\n')
    );
  });
});

describe('formatXlsxMetadata — exact output', () => {
  it('renders every section, with both branches of the defined-name hidden flag', () => {
    const meta: XlsxMetadata = {
      core: { creator: 'V' },
      app: { Application: 'Excel' },
      custom: [{ name: 'C', value: 'cv' }],
      externalRels: [{ source: 's', type: 't', target: 'tg' }],
      definedNames: [
        { name: 'TaxRate', refersTo: 'A1', hidden: false },
        { name: 'Secret', refersTo: 'B2', hidden: true },
      ],
      hiddenSheets: [{ name: 'Sh', state: 'veryHidden' }],
      comments: [{ cell: 'B2', author: 'Al', text: 'check' }],
      threadedComments: [{ cell: 'C3', author: 'Bo', date: 'dt', text: 'review' }],
      people: [{ id: 'p1', displayName: 'Bob', userId: 'bob@x' }],
      macros: ['word/vbaProject.bin'],
    };
    expect(formatXlsxMetadata(meta)).toBe(
      [
        '---',
        '',
        '## Workbook metadata',
        '',
        '### Core properties',
        '',
        '- **creator**: V',
        '',
        '### Application properties',
        '',
        '- **Application**: Excel',
        '',
        '### Custom properties',
        '',
        '| name | value |',
        '| --- | --- |',
        '| C | cv |',
        '',
        '### External relationships',
        '',
        '| source | type | target |',
        '| --- | --- | --- |',
        '| s | t | tg |',
        '',
        '### Defined names',
        '',
        '| name | refersTo | hidden |',
        '| --- | --- | --- |',
        '| TaxRate | A1 |  |',
        '| Secret | B2 | hidden |',
        '',
        '### Hidden / very-hidden sheets',
        '',
        '| name | state |',
        '| --- | --- |',
        '| Sh | veryHidden |',
        '',
        '### Cell comments',
        '',
        '| cell | author | text |',
        '| --- | --- | --- |',
        '| B2 | Al | check |',
        '',
        '### Threaded comments',
        '',
        '| cell | author | date | text |',
        '| --- | --- | --- | --- |',
        '| C3 | Bo | dt | review |',
        '',
        '### People',
        '',
        '| id | displayName | userId |',
        '| --- | --- | --- |',
        '| p1 | Bob | bob@x |',
        '',
        '### Macros (VBA)',
        '',
        MACRO_LINE,
        '',
      ].join('\n')
    );
  });
});

describe('formatPptxMetadata — exact output', () => {
  it('renders every section, with both branches of the slide visibility flag and no --- prefix', () => {
    const meta: PptxMetadata = {
      core: { creator: 'V' },
      app: { Application: 'PowerPoint' },
      custom: [{ name: 'C', value: 'cv' }],
      externalRels: [{ source: 's', type: 't', target: 'tg' }],
      slideTags: [{ source: 'tag1.xml', name: 'STATE', value: 'draft' }],
      commentAuthors: [{ id: '0', name: 'Al', initials: 'A' }],
      comments: [{ author: 'Al', date: 'dt', text: 'fix' }],
      slides: [
        { name: 'slide1.xml', hidden: false, title: 'T1', notes: 'N1' },
        { name: 'slide2.xml', hidden: true, title: 'T2', notes: '' },
      ],
      macros: ['word/vbaProject.bin'],
    };
    expect(formatPptxMetadata(meta)).toBe(
      [
        '## PPTX metadata',
        '',
        '### Core properties',
        '',
        '- **creator**: V',
        '',
        '### Application properties',
        '',
        '- **Application**: PowerPoint',
        '',
        '### Custom properties',
        '',
        '| name | value |',
        '| --- | --- |',
        '| C | cv |',
        '',
        '### External relationships',
        '',
        '| source | type | target |',
        '| --- | --- | --- |',
        '| s | t | tg |',
        '',
        '### Slide tags',
        '',
        '| source | name | value |',
        '| --- | --- | --- |',
        '| tag1.xml | STATE | draft |',
        '',
        '### Comment authors',
        '',
        '| id | name | initials |',
        '| --- | --- | --- |',
        '| 0 | Al | A |',
        '',
        '### Comments',
        '',
        '| author | date | text |',
        '| --- | --- | --- |',
        '| Al | dt | fix |',
        '',
        '### Slides',
        '',
        '| slide | visibility | title | speaker notes |',
        '| --- | --- | --- | --- |',
        '| slide1.xml | visible | T1 | N1 |',
        '| slide2.xml | hidden | T2 |  |',
        '',
        '### Macros (VBA)',
        '',
        MACRO_LINE,
        '',
      ].join('\n')
    );
  });
});
